(4-1)初級 日付フォーマット
rikoysd/ex-vue-emp-manage-bugfix pull request #5
Opened 2022-02-21 07:03 UTC by rikoysd

入社日の日付フォーマットを変更しましたのでレビューをお願いします。

問題があればコメント頂ければと思います。
問題がなければマージをお願いします。

2022-02-21 08:02 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2022-02-21 08:02 UTC, igamasayuki commented on src/views/EmployeeDetail.vue
> +  private dateFormat = format(this.currentEmployee.hireDate, "yyyy年MM月dd日");
行っている処理自体は問題ないのですが、この処理はEmployeeクラスに１つGetterを作成し、その中でフォーマットした文字列を返すように修正をお願いします。

2022-02-21 08:23 UTC, rikoysd commented on src/views/EmployeeDetail.vue
> +  private dateFormat = format(this.currentEmployee.hireDate, "yyyy年MM月dd日");
4-1の修正を行いましたのでレビューお願いします。

2022-02-22 00:30 UTC, igamasayuki approved these changes
とてもわかりやすくなったと思います。
承認します。

2022-02-22 00:30 UTC, merged