(4-2)初級 数値フォーマット
rikoysd/ex-vue-emp-manage-bugfix pull request #6
Opened 2022-02-21 07:40 UTC by rikoysd

4-2が完了しましたのでレビューをお願いします。

問題があればコメントを頂ければと思います。
問題がなければマージをお願いします。

2022-02-21 08:03 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2022-02-21 08:03 UTC, igamasayuki commented on src/views/EmployeeDetail.vue
> +                <span v-html="currentEmployee.salary.toLocaleString()"></span>円
行っている処理自体は問題ないのですが、この処理はEmployeeクラスに１つGetterを作成し、その中でフォーマットした文字列を返すように修正をお願いします。

2022-02-21 08:29 UTC, rikoysd commented on src/views/EmployeeDetail.vue
> +                <span v-html="currentEmployee.salary.toLocaleString()"></span>円
4-2の修正を行いましたのでレビューをお願いします。

2022-02-22 00:31 UTC, igamasayuki approved these changes
気になる点をコメントしました。
承認しますが、必要であれば後ほど修正をしておきましょう。

2022-02-22 00:31 UTC, igamasayuki commented on src/types/employee.ts
> +  public get commaDelimited():string{
TSDocコメントを記載しましょう。

2022-02-22 00:32 UTC, merged