(4-3)初級 パンくずリスト修正
rikoysd/ex-vue-emp-manage-bugfix pull request #7
Opened 2022-02-21 07:52 UTC by rikoysd

4-3が完了しましたのでレビューをお願いします。

問題があればコメントを頂ければと思います。
問題がなければマージをお願いします。

2022-02-21 08:04 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2022-02-21 08:04 UTC, igamasayuki commented on src/views/EmployeeDetail.vue
> +          <router-link to="/employeeList/">従業員リスト</router-link>
class="breadcrumb"を消してしまうとデザインがおかしくなりませんか？

 class="breadcrumb"は消さないようにしてください。

2022-02-21 08:35 UTC, rikoysd commented on src/views/EmployeeDetail.vue
> +          <router-link to="/employeeList/">従業員リスト</router-link>
4-3の修正を行いましたのでレビューをお願いします。

2022-02-22 00:33 UTC, igamasayuki approved these changes
問題ありませんので承認いたします。
プルリクやコミットの粒度がとてもわかりやすいです。

2022-02-22 00:33 UTC, merged